https://www.isaham.my/tv/lw-chart-data/MITRA
https://wzwczlfgmdabfkfosgnz.supabase.co/functions/v1/yahoo-finance   
payload:
{codes: ["5357", "6963", "5555", "5243", "2429"], exchange: "MY"}


https://wzwczlfgmdabfkfosgnz.supabase.co/functions/v1/stock-history
{code: "2429", period: "6m", exchange: "MY"}

https://wzwczlfgmdabfkfosgnz.supabase.co/functions/v1/stock-quarterly
{code: "2429", exchange: "MY"}

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6d2N6bGZnbWRhYmZrZm9zZ256Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2NzYyODAsImV4cCI6MjA5MDI1MjI4MH0.heiGjvC9NMt-JK36xek61PkF81wgoOKA0OyqAvd2mGE

https://www.klsescreener.com/v2/trading_view/symbols?symbol=5099
https://www.klsescreener.com/v2/trading_view/history?symbol=5099&resolution=1D&from=1745366400&to=1785196800&countback=330&currencyCode=MYR

https://wuchang.my/api/stocks/1295/bars?resolution=1D&from=1748822400&to=1785196800

https://klse.i3investor.com/mqtraderapi/app/stk-chart/get-price-hist?timeFrame=day&securityCode=6742&liveDelay=delayed&OriAdj=adj
https://klse.i3investor.com/mqtraderapi/app/stk-chart/get-price-hist?timeFrame=day&securityCode=1155&liveDelay=live&OriAdj=adj

https://klse.i3investor.com/mqtraderapi/tv/delayed/adj/marks?symbol=0041&from=1746403200&to=2114352000&resolution=D
https://klse.i3investor.com/mqtraderapi/tv/delayed/adj/history?symbol=6963&resolution=1D&from=1756512000&to=1785024000&countback=330
https://klse.i3investor.com/mqtraderapi/tv/delayed/adj/symbols?symbol=6963

https://www.malaysiastock.biz/Service1.svc/history?symbol=0020&resolution=1D&from=1720656000&to=1742428800&countback=180&currencyCode=RM

https://stockdata.theedgemalaysia.com/klse/5347/5347_all7.json
https://webapi.theedgemalaysia.com/stocks/relatedNews?stockName=TENAGA
https://stockdata.theedgemalaysia.com/klse/listing/counters.json
https://stockdata.theedgemalaysia.com/klse/5347/5347_compare.json
https://www.shareinvestor.com/api/v1/quote/BURSA:1155/factsheet.json
https://www.shareinvestor.com/api/v1/charts/factsheet_overview_chart_data?id=BURSA:1155&to_retrieve=historical_price&fromdate=20250618&todate=20270716&ciqrandom=1784995439875

https://www.shareinvestor.com/api/v1/charts/c2_charts_data?id=3182.MY&fromdate=20240118&todate=20250423&to_retrieve=historical_price&ciqrandom=1784996057494
https://www.shareinvestor.com/api/v1/charts/c2_charts_data?id=3182.MY&fromdate=20240118&todate=20250423&to_retrieve=historical_price&ciqrandom=1784996057494
https://www.shareinvestor.com/api/v1/charts/c2_charts_data?id=1155.MY&to_retrieve=historical_price&fromdate=20250423&todate=20260726&ciqrandom=1784996238482
https://www.shareinvestor.com/api/v1/charts/c2_charts_data?id=1155.MY&fromdate=20240118&todate=20250423&to_retrieve=historical_price&ciqrandom=1784996238780
https://p2.pickastock.info/TradingView/history?symbol=AIMAX&resolution=1D&from=1741132800&to=1742342400&countback=10
https://p2.pickastock.info/TradingView/history?symbol=AIMAX&resolution=1D&from=1745366400&to=1785196800&countback=330
https://p2.pickastock.info/TradingView/symbols?symbol=AIMAX
https://p1.pickastock.info/api/Stock/Peers?id=AIMAX
https://p1.pickastock.info/api/Post/SocialMedia?key=AIMAX&page=1&rows=4
https://p1.pickastock.info/api/News?symbol=AIMAX&chineseNews=true&englishNews=true&malayNews=true&rows=12
https://p2.pickastock.info/api/QuarterlyReport/0041?page=1&rows=10&annualized=false
https://p1.pickastock.info/api/Stock/Indicators?id=0041&t=D
https://p1.pickastock.info/api/Stock/Similar?symbol=0041&page=1&rows=5
https://p2.pickastock.info/api/RightCard/Prices?securityID=AIMAX&minute=true&mins=5

https://p1.pickastock.info/api/Stock/Symbol/AIMAX

https://p1.pickastock.info/api/Market/KLCI
https://webchart.chartnexus.com/cnxideawebv11/fundamental
payload:  mode=cinfo&counter_key=2_1155

https://theme.chartnexus.com/ginfo/KLSE/1155.txt

x-api key
kls_app_gfZpWmuochzJAfeB8BerrgcBrFrHq-Ik


https://kleverstock-api-422735498549.us-central1.run.app/api/v1/market/price-targets
https://kleverstock-api-422735498549.us-central1.run.app/api/v1/market/fbmklci
https://kleverstock-api-422735498549.us-central1.run.app/api/v1/market/top-active
https://kleverstock-api-422735498549.us-central1.run.app/api/v1/market/bursa-indices
https://api.kleverstock.live/api/news/user-get-news-v2?categories%5B%5D=Business&
https://kleverstock-api-422735498549.us-central1.run.app/api/v1/stocks/0041
https://kleverstock-api-422735498549.us-central1.run.app/api/v1/stocks/0041/price

kls_app_gfZpWmuochzJAfeB8BerrgcBrFrHq-Ik

https://kleverstock-api-422735498549.us-central1.run.app/api/v1/stocks/0041/fundamentals
https://api.kleverstock.live/api/news/user-get-news?tagName=AIMAX&tagType=ticker&active=true&userId=1940&language=EN&isKleverstock=true
https://kleverstock-api-422735498549.us-central1.run.app/api/v1/stocks/0041/ohlcv?period=1Y
https://kleverstock-api-422735498549.us-central1.run.app/api/v1/stocks/0041/price-targets

https://s1.thetradewizard.com/api/v1/tvCharts/history?symbol=AZRB&resolution=5&from=1784701227&to=1784998227&countback=330&currencyCode=MYR
https://s1.thetradewizard.com/v1/tickers.snapshot.fundamentals.get
{"reqs":[{"ticker":"2429","fetag":""}]}

https://s1.thetradewizard.com/v1/tickers.snapshot.technicals.get
{"tickers":["2429"]}
https://s1.thetradewizard.com/v1/ticker.trades.agg?input=%7B%22ticker%22%3A%222429%22%7D


